# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
    inputs:
      SCAN_TYPE:
        description: 'Type of scan to perform'
        required: true
        default: 'Baseline'
        type: choice
        options:
          - Baseline
          - APIS
          - Full
      TARGET:
        description: 'Target URL to scan'
        required: true
        default: 'http://54.167.188.22:3000/'
        type: string
      GENERATE_REPORT:
        description: 'Generate HTML report'
        required: true
        default: true
        type: boolean

env:
  DOCKER_IMAGE: donhadley/chucknorris-jokes
  DOCKERFILE: Dockerfile
  DOCKER_TAG: ${{ github.run_number }}
  EC2_REGION: us-east-1
  EC2_USER: ubuntu
  EC2_HOST: 54.167.188.22
  CONTAINER_NAME: chucknorris-app
  HOST_PORT: 3000
  CONTAINER_PORT: 3000
  SONAR_PROJECT_KEY: nodejs-app-sonar
  SONAR_HOST_URL: http://18.234.225.42:9000/
  TARGET: ${{ github.event.inputs.TARGET || 'http://54.167.188.22:3000/' }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'
 
        cache: 'npm'
    - run: npm ci

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        npm install -g sonar-scanner
        sonar-scanner \
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
          -Dsonar.login=${{ env.SONAR_TOKEN }}
          
    - name: OWASP Dependency-Check
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      run: |
        mkdir -p reports
        docker run --rm \
          -u "$(id -u):$(id -g)" \
          -v "$(pwd)":/src \
          -w /src \
          owasp/dependency-check \
          --project "ChucknorrissApp" \
          --scan /src \
          --format "ALL" \
          --out /src/reports \
          --nvdApiKey "$NVD_API_KEY"



